.include "dict_minimum.inc"
.include "device.inc"
.include "dict_compiler.inc"
.include "dict_interrupt.inc"
.include "words/applturnkey.asm"

.include "words/udot.asm"
.include "words/dot-s.asm"

.include "words/dotstring.asm"
.include "words/squote.asm"
.include "words/show-wordlist.asm"
.include "words/words.asm"

.include "words/edefer.asm"
.include "words/rdefer.asm"
.include "words/is.asm"

.include "words/d-invert.asm"
.include "words/d-plus.asm"
.include "words/d-minus.asm"
.include "words/spirw.asm"


