#!/usr/bin/python

import os
import time

def get_filepaths(directory):
    """
    This function will generate the file names in a directory 
    tree by walking the tree either top-down or bottom-up. For each 
    directory in the tree rooted at directory top (including top itself), 
    it yields a 3-tuple (dirpath, dirnames, filenames).
    """
    file_paths = []  # List which will store all of the full filepaths.

    # Walk the tree.
    for root, directories, files in os.walk(directory):
        for filename in files:
            # Join the two strings in order to form the full filepath.
            filepath = os.path.join(root, filename)
            file_paths.append(filepath)  # Add it to the list.

    return file_paths  # Self-explanatory.

# Run the above function and store its results in a variable.   
full_file_paths = get_filepaths("source/TG")

print """
<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
                      http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

"""
for filename in full_file_paths:
  t = os.stat(filename)[8]
# <url>
#  <loc>http://amforth.sourceforge.net/</loc>
#  <lastmod>2014-07-05T09:36:21Z</lastmod>
#  <priority>0.5000</priority>
# </url>

  print "<url><loc>http://amforth.sourceforge.net/TG/%s</loc><lastmod>%s</lastmod><priority>0.6000</priority</url>" % (filename, time.ctime(t))


print """
</urlset>
"""
